### ISSUE TITLE
3.6 - Sequence Diagram

### ISSUE THREAD

**Issue by NithitLim** [BrianTanJunWei/ICT2201#27]
Create sequence diagram for each UML diagram

**Comment by NithitLim** [comment]
Complete 

![Image](https://user-images.githubusercontent.com/97569173/198820661-1ae162fa-aeab-44d0-9a50-2a83ee3e62a8.png)

**Comment by nikushimi** [comment]
Completed on 28/10/22 with slight overrun 

Reason: There were changes to the Use Case Diagram. Thus needing to reflect the changes in the sequence diagram.
