### ISSUE TITLE
3.5.1 - Class Diagram

### ISSUE THREAD

**Issue by NithitLim** [BrianTanJunWei/ICT2201#28]
Find out what class objects are there from use case description

**Comment by Wai-Kiat** [comment]
24/10/2022: managerViewWorkload updated in the class diagram

**Comment by NithitLim** [comment]
edited


![Image](https://user-images.githubusercontent.com/97569173/198820752-9dcf5560-b175-485a-99c8-899da41d3037.png)

**Comment by NithitLim** [comment]
Completed

![Image](https://user-images.githubusercontent.com/97569173/198821251-3416dc02-76e3-4668-a429-0de0803989c5.png)

**Comment by nikushimi** [comment]
Draft Completed on 22/10/22

Completed on 29/10/22 with overrun

Reason: Slight changes resulted in team updating the class diagram
