### ISSUE TITLE
2.4 - Retrospective (M1)

### ISSUE THREAD

**Issue by BrianTanJunWei** [BrianTanJunWei/ICT2201#32]
• What are the great things that your team is doing?

The team is very cohesive and responsive. Everyone is able to schedule and make time to work on the project together.

• Are there any thing in the team that wish could be changed?
Lesser late night project discussion.
Should have a consistent timing for meeting.
 
• Do you have ideas that could improve the current situation of your team?
Using the github to collaborate better
Self learning how to use github

• As a leader, do the members of the team know the issues you face?
Human relationships, Team cohesiveness, etc

**Comment by nikushimi** [comment]
Completed on 05/10/2022 with no overrun
